### ISSUE TITLE
Provide defmt feature in BSPs to enable atsamd-hal/defmt

### ISSUE THREAD

**Issue by ianrrees** [atsamd-rs/atsamd#810]
In a firmware that depends on a BSP, it's a bit awkward to use defmt for errors that originate in the HAL.  One needs to add the same version of the HAL as the BSP uses to Cargo.toml, to enable the defmt feature.

To resolve this, we should have all the BSPs (at least, that use a new-enough HAL) support a defmt feature themselves.

**Comment by sajattack** [comment]
I think part of the difficulty here is that defmt requires an addition to the linker script?

**Comment by ianrrees** [comment]
I'm not sure I follow - yes using defmt in a firmware requires modifying the linker script, but even with that in place it's not straightforward to use defmt in a firmware that depends on a BSP directly.

For example, if my firmware's Cargo.toml has something like this:

```toml
[dependencies]
metro_m4 = { version = "0.16.1", features = ["usb"] }
```

and in my firmware, I want to use something like:
```Rust
#[derive(Error, defmt::Format, Debug)]
enum Error {
    #[error("UART error:")]
    UartError(hal::sercom::uart::UartError),
   // ...more variants..
}
```

Currently, the only way AFAICT to do this, is to modify Cargo.toml to add a dependency on the HAL, using the same version as the BSP:
```toml
[dependencies.atsamd-hal]
version = "0.20.2"
default-features = false
features = ["defmt"]
```

What I'm proposing is that it would be nice to be able to just do:
```toml
[dependencies]
metro_m4 = { version = "0.16.1", features = ["usb", "defmt"] }
```
